#!/bin/bash

while true; do
  # check to see if there is a connection by pinging a Google server
  if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then
    # if connected, mount the drive and break the loop
    rclone --vfs-cache-mode writes mount OneDrive: /home/dirtygeek/Cloud/OneDrive & 
    rclone --vfs-cache-mode writes mount OneDrivePole: /home/dirtygeek/Cloud/OneDrive_Pole
  else
    # if not connected, wait for one second and then check again
    sleep 1
  fi
done

